### ISSUE TITLE
Travis: look into building in the same directory to speed up cpp build times

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/HaxeManual#172]
This doesn't work right now because of several random `undefined reference` errors (see [here](https://travis-ci.org/Gama11/HaxeManual/jobs/66262037)). That's why each example is built in a separate directory at the moment. Doing fresh builds takes quite a while though.

Ping @hughsando

**Comment by hughsando** [comment]
This looks like a genuine bug with gencpp not correctly setting dependencies on the ```__main__``` or maybe ```__boot__```  class, or potentially something with the way file timestamps are or are not preserved when copying files.  Unless there is something funky with the timestamps, what you are trying to do should work.

**Comment by Simn** [comment]
This is unfortunately still a problem.

**Comment by ibilon** [comment]
I guess this was fixed by https://github.com/HaxeFoundation/HaxeManual/commit/4a786111bd81dfcc60125538d26111b08628132a?

**Comment by Gama11** [comment]
Hm... I guess that fixed the compilation speed issues, but the hxcpp bug is probably still there.

**Comment by Simn** [comment]
Can we close this? Our building times are fine, so whatever issue remains would likely be a hxcpp problem.

**Comment by Gama11** [comment]
Could be moved to the hxcpp repo if it's still an issue.

**Comment by Simn** [comment]
I don't really remember what the issue was though...

**Comment by Gama11** [comment]
Just that building all examples into the same cpp output dir caused errors, don't think anyone's isolated it further.

**Comment by Simn** [comment]
Oh well, I'm sure it's fixed. :P
